- name: Install GitLab
  shell: |
    curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash
    apt-get install -y gitlab-ce

- name: Configure GitLab
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: '^external_url'
    line: "external_url 'http://{{ ansible_hostname }}'"

- name: Reconfigure GitLab
  command: gitlab-ctl reconfigure
